#!/usr/bin/env bash

set -euo pipefail

while getopts t:p: flag; do
    case "$flag" in
        t) language="typescript";;
        p) language="python";;
        *) (echo "unreachable"; exit 1);
    esac
done

command -v deno >/dev/null \
  || (echo "Missing deno" >&2; exit 1)

year=$2
# shellcheck disable=SC2000
len=$(echo "$3" | wc -c)
if [ "$len" == 2 ]; then
    day='0'$3
else
    day=$3
fi
target="./solutions/$language/$year/day$day"

echo "$language $year - day $day"

if [[ $language == "typescript" ]]; then
    target="${target}.ts"
    deno run --allow-read --import-map import_map.json "$target"
fi

if [[ $language == "python" ]]; then
    target="${target}.py"
    python3 "$target"
fi