#!/usr/bin/env bash

set -euo pipefail

command -v deno >/dev/null \
  || (echo "Missing deno" >&2; exit 1)

year=$1
# shellcheck disable=SC2000
len=$(echo "$2" | wc -c)
if [ "$len" == 2 ]; then
    day='0'$2
else
    day=$2
fi
target="./solutions/$year/day$day"

echo "$year - day $day"
target="${target}.ts"
deno run --allow-read --import-map import_map.json "$target"
